### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by kwonoj** [kwonoj/docker-icu-wasm#2]
- [ ] align build config to chromium/third_party build.gn
- [ ] makefile for worditerator
- [ ] data file log in worditerator
- [ ] size reduction in general
